language: perl
sudo: false
perl:
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
env:
  global:
    - secure: "CsaiWlggkREyMQRBMp+dZHAmFGJMzVeH/dyaIEpPN6Equc4+don2VpFzCG97v2dwX4Arj6h9EB/Y6FgezJo9lYKSexkRXIBXEuAIe1ziCOUUm1FiHGxMG1S8whP5czyholCk4WwJAAILtxviyioZWLGErX3ilF55Mgofpoq3Sz0sD4Bajf6hGcCrIAsjasWiHe0EI6DlkAiGNMuaqLXJ5HCh4E8AtJ30wwc2MvXKg9QJTwtEZ2ZMgqG1KZCQOwGeiFLgoZsHMJD7HLCn3cUWHNR9EE690jAIeysuESDLWs/5pi1NWsnkvfKHX/0DLqCA0k0/ANzDeMUp/QwWfUp3ud36Q/gNPGTi1UrDoCshJzCzI9epcelWJk+g8CAGBoenYfslDylTstKaPXeIqQvHmGAzQs3CZNHRi9lGg3bZv7QHV27feQE9VZOYdTY5ToFWXEvOccId6JWkCaL0wxQgXOb5AF9rup6OXo1HbqKevtYz6i3EfSBTaYX2F9HrlDL7vIReGm22dEejLNbx4CpIoS63yaK1VlVlu46akvlCUGT3J/uoS+XBqh/pLKwB5RULro92xwjyR9Syt1dpWSdKmmZ4yVGvVqXwttDCCc7u9NGvR2wGiXuCW+xgeWaGQ015G1upFXoK8NMsEdMzhJ1SJbDq6UeddZql+Pw1BZE8W5I="
