language: perl
sudo: false
perl:
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
env:
  global:
    - secure: "Quk8M9CdLut+NbW3zkTRj46LcOe8z+UzzACuoajleOtJNlXgd6qStzrO/ueqM5zGSsSqPCGHFpXRs0gO/H+Vtpv2JbfqdTWagYotBnFser/d+VjUZSeJSKtWIu3tEt8Ru//zEahWrHYTnQ6Pxa1FczOgAiYWwX039IxNlgHe5YH4H0gsUdj3Co89k8HEYAr6G9WWz9MFjVGFZJwi4AvaSXXYWWzaT/VP80KtLiaC4qjOAjWhlgeBvxzH79Dmj0Viwl6NDL2zf9xACbv0xAf0ePfbQfxG3K25c6G5ZCUO4jDCFSw0su4czKJcxmMonZULrrZXqBrrF6AnH/LjxtIlfRFHgaIQ6JyIeHQvjGTVnTKS0uavZwZhz8ld6LoDfZplkPbVbmvGgZv//jC+dnMDpJmKwiwHcutN+g4C6XW8EiWFh/Jp5YNZaQDo2dY1V7cvoSqJEs0OpWacHTCKA6jMRTZBe4KCVSKZIjnqsQNEac1259whBwkNjSecdRbDSwUXxVOMODUhRObk2svAX5FPm99B4UqOs1EJh0Pjnbq/TVkpFFmPNgAjD2gIBzwaPuDXOZQTSvmlx1oS3Xjiw87FJiQiYupmNY3CMkLVAaXQ9xn12mbUT74Fp1XFWC6ssiCHHSEEz1Lcint9pKJQbmPTeSS3SPXXjzPhDtsyfPVJthk="
