language: perl
sudo: false
perl:
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
env:
  global:
    - secure: "GCUgDaiwCvf7tsymjXXupQIxmf1FG32SmjALSIEaSB7ajMYjAE24BTvVhzw18D0BceukWQ4SAcd4VN7N1PkKq6elYMlYGvbAbEPy8WEQB4M3ivbrnRevdqaE5VEVHMP+Y+5EfVVF2ddNoDm0EkcxkygEM6LT+sM5FZCfMqRpRKzRbdTIccryMEshFkeTU14sm/i08wZA8xXN6PucM+s6qmhdRnE77L4ghoi/gdXHhLmwa935Fct+SojWruuVoHFgRvK9QT6dZwJTB8VZnPznKkk0hczH3ph07O8KcxvmsTejR4lQq+ZlsxWXApsTOo+DXLDYnc9ubx54/LWo9EhckYQ7nDqMLPudH27ma6N1Js6FHSgsgh5beWGGJfUcDyrKi595BoKR/nbm9FB/QsnFNjtKKlAkS2cKJfHp1RT7mynR6Fg8so3nHDOlSfAESNKuOWm04+z8B/SyrgYAB9URO7XAVCDjDLvh63HqaJzsSarOu53RNjJmwh4xBlsWswdFrRMh14b5ymCjMfcmXBXzv1kS7rffq7E7+7s83FjJ1RppHKeCEuCPb4nVv//bSnBzY61YWcYS13QcBem5mpMmCkXJaXDPnnpApncJQuY4KbF6VXVyAL5iXzzgDxEpvkkZ4C+jbpizcyfouIkH0KitOcwRIcS+vy+RfmFwVuE+mp4="
