language: perl
sudo: false
perl:
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
env:
  global:
    - secure: "de3xqrH/jhQ69UpO/mss9lpLq2ahbBRpSQl1reIULvc7wnxS6V8U3Lhr/pt6gUwMlFPw7v6AO4nzYqJnX3NqTHR+3vT6nKSiqziibHQ9LJSKm35JoflBAzJ/cxdwOf0IUBmfy7K/TAjTSJ80xItMZZEs2HGQx+p9zBoWgzWDxgfnOOBEYG/7vPvuZFZhGYf11+QEhfeSbSDNdaFi+nUWI0lA3oGfxWtHzgsTaREz9F/aah8VkBVw+xhFc+/4QcRtIUYuUaM6o8PwSaYmtDaT9F8dNMEsCZ8lWGee8db80xqtRu/wl7C5xQT+TMePfOy5leKyThizD+aH2J0drJWacNnJjoVMNcZwDxTghgPwPoSz9SZZFVbShqUI/JMNLwdQF35/DPLN6M67vNlWt5wO/DAO+AkUVcBhKlXqIJlK+xs4owPT5Q6ZhP68JK8TPKjD9TwY9UGBjNMWCZYnL931ahMxHop+hQcC8vQVPf+esvQQouTPq+O/iuMNNOKi3B0aMXTRqOc52ywKP6wa79lfg6o/VpgONYllwcUPRaz4O+6+oTLIYS1kbNTme0w0HrLLHtEBBWjlz7Dak6BlxQS0ppjHC4mX2DtZq1XqUZNZZjhrnbCa1XLqwZOC48smujLkj7RTXiPTqf5a249oLVGsMcfz6QYPBDN04r+2n7R9V7w="
